- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - nginx

- name: Configure Reverse Proxy
  ansible.builtin.template:
    src: roles/nginx/templates/default.conf.j2
    dest: "/etc/nginx/sites-available/default"
    owner: "root"
    group: "root"
    mode: "0777"

- name: Create a symbolic link
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    owner: "root"
    group: "root"
    state: link

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

