- name: Configure sonar Reverse Proxy
  ansible.builtin.template:
    src: roles/grafana/templates/grafana.conf.j2
    dest: "/etc/nginx/sites-available/grafana.conf"
    owner: "root"
    group: "root"
    mode: "0755"
