- name: Nginx CertBot HTTPS Installation
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /opt/ansible-venv/bin/python
# either nginx or certbot
  roles:
    - nginx
    # - certbot
