- name: Install Cert Manager
  hosts: localhost
  become: true

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - snapd
          - nginx

    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Install Snapd Core
      community.general.snap:
        name:
          - core

    - name: Install Snapd Certbot
      community.general.snap:
        name:
          - certbot
        classic: true

    - name: Install python3 nginx certbot
      ansible.builtin.apt:
        name:
          - python3-certbot-nginx

    - name: Generate HTTPS Certificate
      register: generate_cert
      changed_when: generate_cert.rc != 0
      ansible.builtin.shell: |
        certbot --nginx -n --agree-tos -d rhattox.ddns.net -m bruno02souto@gmail.com
      args:
        executable: /bin/bash

    - name: Enable Renew
      register: renew_cert
      changed_when: renew_cert.rc != 0
      ansible.builtin.shell: |
        certbot renew --dry-run
      args:
        executable: /bin/bash
