- name: Configure sonar Reverse Proxy
  ansible.builtin.template:
    src: roles/sonar/templates/sonar.conf.j2
    dest: "/etc/nginx/sites-available/sonar.conf"
    owner: "root"
    group: "root"
    mode: "0755"
